spring:
  application:
    name: NeoPoth

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ""
    url: jdbc:mysql://localhost:3306/neopoth

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
